name: IaC Workflow (Terraform)

run-name: Terraform ${{ inputs.action }}

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform action"
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

      env:
        type: choice
        options:
            - dev
            - prod

jobs:
  terraform-actions:
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
    

      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Plan
        if: ${{ inputs.action == 'plan' }}
        working-directory: ./infra
        run: terraform plan

      - name: Terraform Apply
        if: ${{ inputs.action == 'apply' }}
        working-directory: ./infra
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ inputs.action == 'destroy' }}
        working-directory: ./infra
        run: terraform destroy -auto-approve
